from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from CONTROLADORES.control_clie import ClieController


class Ui_clientes(object):

    def __init__(self):
        self.controlador =   ClieController(self)


    def setupUi(self, clientes):
        clientes.setObjectName("clientes")
        clientes.resize(683, 417)
        font = QtGui.QFont()
        font.setPointSize(19)
        clientes.setFont(font)
        clientes.setStyleSheet("")
        self.Opciones = QtWidgets.QTabWidget(clientes)
        self.Opciones.setGeometry(QtCore.QRect(0, -20, 691, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Opciones.sizePolicy().hasHeightForWidth())
        self.Opciones.setSizePolicy(sizePolicy)
        self.Opciones.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.Opciones.setObjectName("Opciones")
        self.OpcionesPage1_2 = QtWidgets.QWidget()
        self.OpcionesPage1_2.setObjectName("OpcionesPage1_2")
        self.table_mos_clien = QtWidgets.QTableWidget(self.OpcionesPage1_2)
        self.table_mos_clien.setGeometry(QtCore.QRect(10, 110, 551, 261))
        self.table_mos_clien.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_mos_clien.setObjectName("table_mos_clien")
        self.table_mos_clien.setColumnCount(5)
        self.table_mos_clien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_mos_clien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_mos_clien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_mos_clien.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_mos_clien.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_mos_clien.setHorizontalHeaderItem(4, item)
        self.b_buscar = QtWidgets.QPushButton(self.OpcionesPage1_2)
        self.b_buscar.setGeometry(QtCore.QRect(200, 60, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.b_buscar.setFont(font)
        self.b_buscar.setStyleSheet("    background-color: rgb(93, 179, 255);\n"
"\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"padding: 10px;\n"
"border-radius: 12px;\n"
"\n"
"")
        self.b_buscar.setObjectName("b_buscar")
        self.e_codi = QtWidgets.QLineEdit(self.OpcionesPage1_2)
        self.e_codi.setGeometry(QtCore.QRect(40, 60, 141, 41))
        self.e_codi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #000000;\n"
"padding: 10px;\n"
"border-radius: 12px;")
        self.e_codi.setText("")
        self.e_codi.setObjectName("e_codi")
        self.layoutWidget = QtWidgets.QWidget(self.OpcionesPage1_2)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 110, 101, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_refrecar = QtWidgets.QPushButton(self.layoutWidget)
        self.b_refrecar.setStyleSheet("    background-color: rgb(93, 179, 255);\n"
"    border: 2px solid #fff;\n"
"    color: #fff;\n"
"    padding: 10px;\n"
"    border-radius: 12px;\n"
"")
        self.b_refrecar.setObjectName("b_refrecar")
        self.verticalLayout.addWidget(self.b_refrecar)
        self.b_actualizar = QtWidgets.QPushButton(self.layoutWidget)
        self.b_actualizar.setStyleSheet("background-color: rgb(93, 179, 255);\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"padding: 10px;\n"
"border-radius: 12px;\n"
"")
        self.b_actualizar.setObjectName("b_actualizar")
        self.verticalLayout.addWidget(self.b_actualizar)
        self.b_eliminar = QtWidgets.QPushButton(self.layoutWidget)
        self.b_eliminar.setStyleSheet("    background-color: rgb(93, 179, 255);\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"padding: 10px;\n"
"border-radius: 12px;\n"
"")
        self.b_eliminar.setObjectName("b_eliminar")
        self.verticalLayout.addWidget(self.b_eliminar)
        self.T_agre_clie_2 = QtWidgets.QWidget(self.OpcionesPage1_2)
        self.T_agre_clie_2.setGeometry(QtCore.QRect(70, 10, 531, 41))
        self.T_agre_clie_2.setStyleSheet("background-color: rgb(85, 79, 255);\n"
"border-radius: 20px;")
        self.T_agre_clie_2.setObjectName("T_agre_clie_2")
        self.label_2 = QtWidgets.QLabel(self.T_agre_clie_2)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Opciones.addTab(self.OpcionesPage1_2, "")
        self.OpcionesPage2_2 = QtWidgets.QWidget()
        self.OpcionesPage2_2.setObjectName("OpcionesPage2_2")
        self.T_agre_clie = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.T_agre_clie.setGeometry(QtCore.QRect(50, 80, 241, 41))
        self.T_agre_clie.setStyleSheet("background-color: rgb(85, 79, 255);\n"
"border-radius: 20px;")
        self.T_agre_clie.setObjectName("T_agre_clie")
        self.label = QtWidgets.QLabel(self.T_agre_clie)
        self.label.setGeometry(QtCore.QRect(70, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 150, 261, 186))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.t_idclie = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_idclie.setFont(font)
        self.t_idclie.setAlignment(QtCore.Qt.AlignCenter)
        self.t_idclie.setObjectName("t_idclie")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t_idclie)
        self.e_idclie = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.e_idclie.setFont(font)
        self.e_idclie.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e_idclie.setText("")
        self.e_idclie.setFrame(True)
        self.e_idclie.setObjectName("e_idclie")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.e_idclie)
        self.t_nombre = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_nombre.setFont(font)
        self.t_nombre.setAlignment(QtCore.Qt.AlignCenter)
        self.t_nombre.setObjectName("t_nombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t_nombre)
        self.e_nombre = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.e_nombre.setFont(font)
        self.e_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e_nombre.setObjectName("e_nombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.e_nombre)
        self.t_apellido = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_apellido.setFont(font)
        self.t_apellido.setAlignment(QtCore.Qt.AlignCenter)
        self.t_apellido.setObjectName("t_apellido")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.t_apellido)
        self.t_direccion = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_direccion.setFont(font)
        self.t_direccion.setAlignment(QtCore.Qt.AlignCenter)
        self.t_direccion.setObjectName("t_direccion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.t_direccion)
        self.t_telefono = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_telefono.setFont(font)
        self.t_telefono.setAlignment(QtCore.Qt.AlignCenter)
        self.t_telefono.setObjectName("t_telefono")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.t_telefono)
        self.e_telefono = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.e_telefono.setFont(font)
        self.e_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e_telefono.setObjectName("e_telefono")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.e_telefono)
        self.e_direccion = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.e_direccion.setFont(font)
        self.e_direccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e_direccion.setObjectName("e_direccion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.e_direccion)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.b_agregar = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_agregar.setFont(font)
        self.b_agregar.setStyleSheet("    background-color: rgb(93, 179, 255);\n"
"\n"
"    border: 2px solid #fff;\n"
"    color: #fff;\n"
"    padding: 10px;\n"
"    border-radius: 12px;\n"
"")
        self.b_agregar.setObjectName("b_agregar")
        self.verticalLayout_2.addWidget(self.b_agregar)
        self.T_agre_clie_4 = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.T_agre_clie_4.setGeometry(QtCore.QRect(80, 20, 531, 41))
        self.T_agre_clie_4.setStyleSheet("background-color: rgb(85, 79, 255);\n"
"border-radius: 20px;")
        self.T_agre_clie_4.setObjectName("T_agre_clie_4")
        self.label_5 = QtWidgets.QLabel(self.T_agre_clie_4)
        self.label_5.setGeometry(QtCore.QRect(200, 0, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.T_agre_clie_3 = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.T_agre_clie_3.setGeometry(QtCore.QRect(370, 80, 241, 41))
        self.T_agre_clie_3.setStyleSheet("background-color: rgb(85, 79, 255);\n"
"border-radius: 20px;")
        self.T_agre_clie_3.setObjectName("T_agre_clie_3")
        self.label_4 = QtWidgets.QLabel(self.T_agre_clie_3)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(360, 200, 274, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.t_idclie_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_idclie_2.setFont(font)
        self.t_idclie_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_idclie_2.setObjectName("t_idclie_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t_idclie_2)
        self.t_nombre_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_nombre_2.setFont(font)
        self.t_nombre_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_nombre_2.setObjectName("t_nombre_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t_nombre_2)
        self.t_apellido_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_apellido_2.setFont(font)
        self.t_apellido_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_apellido_2.setObjectName("t_apellido_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.t_apellido_2)
        self.t_direccion_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_direccion_2.setFont(font)
        self.t_direccion_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_direccion_2.setObjectName("t_direccion_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.t_direccion_2)
        self.t_telefono_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.t_telefono_2.setFont(font)
        self.t_telefono_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_telefono_2.setObjectName("t_telefono_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.t_telefono_2)
        self.Tex_ID = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Tex_ID.setFont(font)
        self.Tex_ID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tex_ID.setText("")
        self.Tex_ID.setObjectName("Tex_ID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Tex_ID)
        self.Tex_Nom = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Tex_Nom.setFont(font)
        self.Tex_Nom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tex_Nom.setText("")
        self.Tex_Nom.setObjectName("Tex_Nom")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Tex_Nom)
        self.Text_Tipo = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Text_Tipo.setFont(font)
        self.Text_Tipo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Text_Tipo.setText("")
        self.Text_Tipo.setObjectName("Text_Tipo")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Text_Tipo)
        self.Text_Pag = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Text_Pag.setFont(font)
        self.Text_Pag.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Text_Pag.setText("")
        self.Text_Pag.setObjectName("Text_Pag")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Text_Pag)
        self.Tex_deuda = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Tex_deuda.setFont(font)
        self.Tex_deuda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tex_deuda.setText("")
        self.Tex_deuda.setObjectName("Tex_deuda")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Tex_deuda)
        self.layoutWidget3 = QtWidgets.QWidget(self.OpcionesPage2_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(380, 150, 221, 42))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.e_codi_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.e_codi_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #000000;\n"
"padding: 10px;\n"
"border-radius: 12px;")
        self.e_codi_2.setText("")
        self.e_codi_2.setObjectName("e_codi_2")
        self.horizontalLayout.addWidget(self.e_codi_2)
        self.b_buscar_2 = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.b_buscar_2.setFont(font)
        self.b_buscar_2.setStyleSheet("    background-color: rgb(93, 179, 255);\n"
"\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"padding: 10px;\n"
"border-radius: 12px;\n"
"\n"
"")
        self.b_buscar_2.setObjectName("b_buscar_2")
        self.horizontalLayout.addWidget(self.b_buscar_2)
        self.Opciones.addTab(self.OpcionesPage2_2, "")

        self.retranslateUi(clientes)
        self.Opciones.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(clientes)


        #----------------BOTONES--------------------------#
        self.mos = self.b_refrecar.clicked.connect(lambda:self.controlador.list_Clie())
        self.agre = self.b_agregar.clicked.connect(lambda:self.controlador.insert_Clie(self.e_idclie.text(),self.e_nombre.text(),self.e_direccion.text(),str(self.comboBox.currentText()),self.e_telefono.text()))   
        self.act = self.b_actualizar.clicked.connect(lambda:self.controlador.act_Clie())
        self.bus = self.b_buscar.clicked.connect(lambda:self.controlador.bus_Clie(self.e_codi.text()))
        self.eliemp = self.b_eliminar.clicked.connect(lambda:self.controlador.delete_Clie())
        self.clie = self.b_buscar_2.clicked.connect(lambda:self.controlador.clie_abn_pen(self.e_codi_2.text()))



    def retranslateUi(self, clientes):
        _translate = QtCore.QCoreApplication.translate
        clientes.setWindowTitle(_translate("clientes", "clientes"))
        item = self.table_mos_clien.horizontalHeaderItem(0)
        item.setText(_translate("clientes", "ID CLIENTE"))
        item = self.table_mos_clien.horizontalHeaderItem(1)
        item.setText(_translate("clientes", "NOMBRE "))
        item = self.table_mos_clien.horizontalHeaderItem(2)
        item.setText(_translate("clientes", "TIPO"))
        item = self.table_mos_clien.horizontalHeaderItem(3)
        item.setText(_translate("clientes", "DIRECCION"))
        item = self.table_mos_clien.horizontalHeaderItem(4)
        item.setText(_translate("clientes", "TELEFONO"))
        self.b_buscar.setText(_translate("clientes", "BUSCAR"))
        self.e_codi.setPlaceholderText(_translate("clientes", "ID"))
        self.b_refrecar.setText(_translate("clientes", "REFRESCAR"))
        self.b_actualizar.setText(_translate("clientes", "ACTUALIZAR"))
        self.b_eliminar.setText(_translate("clientes", "ELIMINAR"))
        self.label_2.setText(_translate("clientes", "CLIENTE"))
        self.label.setText(_translate("clientes", "AGREGAR"))
        self.t_idclie.setText(_translate("clientes", "ID CLIENTE*:"))
        self.t_nombre.setText(_translate("clientes", "NOMBRE*:"))
        self.t_apellido.setText(_translate("clientes", "TIPO*:"))
        self.t_direccion.setText(_translate("clientes", "DIRECCION:"))
        self.t_telefono.setText(_translate("clientes", "TELEFONO*:"))
        self.comboBox.setItemText(0, _translate("clientes", "EMPRESA"))
        self.comboBox.setItemText(1, _translate("clientes", "INDIVIDUO"))
        self.b_agregar.setText(_translate("clientes", "AGREGAR"))
        self.label_5.setText(_translate("clientes", "CLIENTE"))
        self.label_4.setText(_translate("clientes", "PAGO Y DEUDA"))
        self.t_idclie_2.setText(_translate("clientes", "ID CLIENTE:"))
        self.t_nombre_2.setText(_translate("clientes", "NOMBRE:"))
        self.t_apellido_2.setText(_translate("clientes", "TIPO:"))
        self.t_direccion_2.setText(_translate("clientes", "PAGADO:"))
        self.t_telefono_2.setText(_translate("clientes", "DEUDA:"))
        self.e_codi_2.setPlaceholderText(_translate("clientes", "ID"))
        self.b_buscar_2.setText(_translate("clientes", "BUSCAR"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QMainWindow()
    ui = Ui_clientes()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())


