import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from CONTROLADORES.control_login import LoginController
from UIS.UI_menu import Ui_menu_principal

class Ui_LogIn(object):
    def __init__(self):
        self.login_controller = LoginController(self)

    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(595, 215)
        LogIn.setMaximumSize(QtCore.QSize(324324, 423423))
        LogIn.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LogIn)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, -40, 241, 341))
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setStyleSheet("border-image: url(:/imagenes/jeans-4517867__340.jpg);")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 10, 369, 175))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_user = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_user.setFont(font)
        self.input_user.setObjectName("input_user")
        self.gridLayout.addWidget(self.input_user, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.ICONO = QtWidgets.QPushButton(self.layoutWidget)
        self.ICONO.setEnabled(True)
        self.ICONO.setMinimumSize(QtCore.QSize(5, 5))
        self.ICONO.setMaximumSize(QtCore.QSize(234324, 2344))
        font = QtGui.QFont()
        font.setKerning(True)
        self.ICONO.setFont(font)
        self.ICONO.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ICONO.setStyleSheet("background-color: rgb(246, 255, 243);\n"
"border: None;\n"
"")
        self.ICONO.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.ICONO.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/jeans-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ICONO.setIcon(icon)
        self.ICONO.setIconSize(QtCore.QSize(50, 50))
        self.ICONO.setObjectName("ICONO")
        self.gridLayout.addWidget(self.ICONO, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_password.setFont(font)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.gridLayout.addWidget(self.input_password, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.btn_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        LogIn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LogIn)
        self.statusbar.setObjectName("statusbar")
        LogIn.setStatusBar(self.statusbar)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)
        #----------------BOTONES--------------------------#
        self.x = self.btn_login.clicked.connect(lambda:self.login_controller.logIn(self.input_user.text(),self.input_password.text(),Ui_menu_principal,LogIn))
  

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "LOGIN"))
        self.input_user.setPlaceholderText(_translate("LogIn", "usuario"))
        self.label_3.setText(_translate("LogIn", "Contraseña:"))
        self.label.setText(_translate("LogIn", "Iniciar Sesión"))
        self.label_2.setText(_translate("LogIn", "Usuario:"))
        self.input_password.setPlaceholderText(_translate("LogIn", "contraseña"))
        self.btn_login.setText(_translate("LogIn", "Entrar"))


import IMAGENES.ima

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QMainWindow()
    ui = Ui_LogIn()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())
